import {
  PAGES_CONTENT,
  SKILLS,
  HIGHLIGHTS,
  type Highlight,
  HERO_SOCIAL_LINKS,
  CONTACT_SOCIAL_LINKS,
  type SocialIcon,
  TECH_STACK,
  type Tech,
  PROFESSIONAL_PROJECTS,
  PERSONAL_PROJECTS,
  type Project,
} from "@/data/portfolio";

export function usePortfolioData() {
  return {
    author: PAGES_CONTENT.author,
    heroSubtitle: PAGES_CONTENT.hero_subtitle,
    heroSocialIcons: HERO_SOCIAL_LINKS as SocialIcon[],
    aboutMeTitle: PAGES_CONTENT.about_me_title,
    aboutMeTitleHighlight: PAGES_CONTENT.about_me_title_highlight,
    aboutMeSubtitle: PAGES_CONTENT.about_me_subtitle,
    aboutMeDescription: PAGES_CONTENT.about_me_description,
    skills: SKILLS as string[],
    highlights: HIGHLIGHTS as Highlight[],
    projectsTitle: PAGES_CONTENT.projects_title,
    projectsTitleHighlight: PAGES_CONTENT.projects_title_highlight,
    projectsSubtitle: PAGES_CONTENT.projects_subtitle,
    professionalTitle: PAGES_CONTENT.professional_title,
    professionalTitleSuffix: PAGES_CONTENT.professional_title_suffix,
    professionalProjectsSubtitle: PAGES_CONTENT.professional_projects_subtitle,
    personalTitle: PAGES_CONTENT.personal_title,
    personalTitleHighlight: PAGES_CONTENT.personal_title_highlight,
    personalTitleSuffix: PAGES_CONTENT.personal_title_suffix,
    personalProjectsSubtitle: PAGES_CONTENT.personal_projects_subtitle,
    professionalProjects: PROFESSIONAL_PROJECTS as Project[],
    personalProjects: PERSONAL_PROJECTS as Project[],
    projects: [...PROFESSIONAL_PROJECTS, ...PERSONAL_PROJECTS] as Project[],
    techStack: TECH_STACK as Tech[],
    contactSocialIcons: CONTACT_SOCIAL_LINKS as SocialIcon[],
    contactTitle: PAGES_CONTENT.contact_title,
    contactTitleHighlight: PAGES_CONTENT.contact_title_highlight,
    contactText: PAGES_CONTENT.contact_text,
    contactLocation: PAGES_CONTENT.contact_location,
    viewProjectsLabel: PAGES_CONTENT.view_projects,
    downloadResumeLabel: PAGES_CONTENT.download_resume,
    footerText: PAGES_CONTENT.footer_text,
  };
}
